# Generated by Django 5.0.6 on 2024-05-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0002_region_comuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='nombre',
            new_name='name',
        ),
    ]
