# Generated by Django 5.0.6 on 2024-05-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0003_rename_nombre_comuna_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='nombre',
            new_name='name',
        ),
    ]
