# Generated by Django 5.0.6 on 2024-05-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0004_rename_nombre_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='nombre',
        ),
    ]
